/**
 * Pokémon availability service
 * Layer 5: Service/IO adapter
 * 
 * Uses precomputed availability data from static JSON files.
 * Data is generated by: yarn generate:availability
 */

import type { AvailabilityData } from "~/data/availability/types";

/**
 * Cache for loaded availability data
 * Key: gameId (e.g., "red", "firered")
 */
const availabilityCache = new Map<string, Set<string>>();

/**
 * Vite glob import for all availability JSON files
 * This allows Vite to analyze and bundle the files at build time
 */
const availabilityModules = import.meta.glob<AvailabilityData>(
  "../../data/availability/*.json",
  { eager: false }
);

/**
 * Load availability data for a specific game
 * Uses Vite's glob import for proper bundling
 */
async function loadAvailabilityData(gameId: string): Promise<Set<string>> {
  // Check cache first
  if (availabilityCache.has(gameId)) {
    return availabilityCache.get(gameId)!;
  }

  try {
    // Find the matching module path (relative from this file)
    const modulePath = `../../data/availability/${gameId}.json`;
    const moduleLoader = availabilityModules[modulePath];
    
    if (!moduleLoader) {
      console.warn(`No availability data found for game: ${gameId}`);
      return new Set();
    }

    // Load the JSON data
    const data = await moduleLoader();

    // Convert array to Set for O(1) lookups
    const obtainableSet = new Set(data.obtainable);
    availabilityCache.set(gameId, obtainableSet);

    return obtainableSet;
  } catch (error) {
    console.error(`Failed to load availability data for ${gameId}:`, error);
    // Return empty set if data file doesn't exist
    return new Set();
  }
}

/**
 * Map version names to game IDs
 * Some versions share the same data (e.g., red-jp and red both use "red")
 */
function versionToGameId(version: string): string {
  // Handle Japanese versions that share data with international versions
  const versionMap: Record<string, string> = {
    "red": "red",
    "blue": "blue", 
    "green": "green",
    "yellow": "yellow",
    "gold": "gold",
    "silver": "silver",
    "crystal": "crystal",
    "ruby": "ruby",
    "sapphire": "sapphire",
    "emerald": "emerald",
    "firered": "firered",
    "leafgreen": "leafgreen",
    "diamond": "diamond",
    "pearl": "pearl",
    "platinum": "platinum",
    "heartgold": "heartgold",
    "soulsilver": "soulsilver",
    "black": "black",
    "white": "white",
    "black-2": "black-2",
    "white-2": "white-2",
  };

  return versionMap[version] || version;
}

/**
 * Check if a Pokémon is obtainable in a specific game version
 */
export async function isPokemonObtainable(
  speciesName: string,
  version: string
): Promise<boolean> {
  const gameId = versionToGameId(version);
  const obtainableSet = await loadAvailabilityData(gameId);
  return obtainableSet.has(speciesName);
}

/**
 * Filter a list of Pokémon to only those obtainable in a specific version
 * This is now extremely fast since we're just doing Set lookups
 */
export async function filterObtainablePokemon(
  speciesNames: string[],
  version: string
): Promise<string[]> {
  const gameId = versionToGameId(version);
  const obtainableSet = await loadAvailabilityData(gameId);
  
  return speciesNames.filter((name) => obtainableSet.has(name));
}
